//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETMUAHANG
    {
        public long Id { get; set; }
        public Nullable<long> IdKhachHang { get; set; }
        public Nullable<long> IdMuaHang { get; set; }
        public Nullable<double> SoTienConLai { get; set; }
        public Nullable<decimal> ChuoiNgayTra { get; set; }
        public string NgayTra { get; set; }
        public Nullable<long> DaHoanThanh { get; set; }
    }
}
