//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DienMayThanhDanhEntities : DbContext
    {
        private static string Config = "metadata=res://*/DataBase.DienMay.csdl|"
                  + "res://*/DataBase.DienMay.ssdl|res://*/DataBase.DienMay.msl;" +
                  "provider=System.Data.SQLite.EF6;provider connection string=data source=";
        public static string startupPath = System.IO.Path.GetDirectoryName(
System.Reflection.Assembly.GetExecutingAssembly().Location) + "\\Data\\Database\\DienMayThanhDanh.db;";
        public static string startupPathBackup = System.IO.Path.GetDirectoryName(
System.Reflection.Assembly.GetExecutingAssembly().Location) + "\\Data\\Backups\\DienMayThanhDanh.db;";
        public DienMayThanhDanhEntities()
            : base(Config + startupPath)
        {

        }
        public DienMayThanhDanhEntities(string s) : base(Config + s)
        {

        }
        public DienMayThanhDanhEntities(bool tr) : base(Config + startupPathBackup)
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }



        public virtual DbSet<CHITIETMUAHANG> CHITIETMUAHANGs { get; set; }
        public virtual DbSet<CHITIETVAYLAI> CHITIETVAYLAIs { get; set; }
        public virtual DbSet<HINHTHUC> HINHTHUCs { get; set; }
        public virtual DbSet<KHACHANG> KHACHANGs { get; set; }
        public virtual DbSet<KHACHHANGVAYLAI> KHACHHANGVAYLAIs { get; set; }
        public virtual DbSet<MUAHANG> MUAHANGs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<TRANGTHAI> TRANGTHAIs { get; set; }
        public virtual DbSet<VAYLAI> VAYLAIs { get; set; }
    }
}
