//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANGVAYLAI
    {
        public long Id { get; set; }
        public string TenKhachHang { get; set; }
        public string SoCMND { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string TaiSanTheChap { get; set; }
        public long TrangThai { get; set; }
    }
}
