//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUAHANG
    {
        public long Id { get; set; }
        public long IdKhachHang { get; set; }
        public decimal ChuoiNgayMua { get; set; }
        public double NgayMua { get; set; }
        public string TenSanPham { get; set; }
        public double GiaSanPham { get; set; }
        public double TraTruoc { get; set; }
        public double ConLai { get; set; }
        public long SoThangTra { get; set; }
    }
}
