//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUAHANG
    {
        public long Id { get; set; }
        public Nullable<long> IdKhachHang { get; set; }
        public Nullable<decimal> ChuoiNgayMua { get; set; }
        public Nullable<double> NgayMua { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<double> GiaSanPham { get; set; }
        public Nullable<double> TraTruoc { get; set; }
        public Nullable<double> ConLai { get; set; }
        public Nullable<long> SoThangTra { get; set; }
    }
}
