//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public long Id { get; set; }
        public string TaiKhoan1 { get; set; }
        public string MatKhau { get; set; }
    }
}
