//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAYLAI
    {
        public long Id { get; set; }
        public long SoLai { get; set; }
        public long SoThangVay { get; set; }
        public string NgayVay { get; set; }
        public long IdKhachHangVay { get; set; }
        public long SoTienVay { get; set; }
    }
}
